POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "hello,up dolly",
  "year": 2011,
  "plot": "nothing important",
  "director": "bob saget",
  "english": true
}

###
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name":"l",
  "last_name":"snider",
  "gender":"male",
  "age":"13",
  "known_for":"something"
}

### updating actors
PATCH http://localhost:3000/movies/14.json
Content-Type: application/json

{
  "title":"l",
  "year":"1222",
  "english": "false",
  "director": "larry"
}

###
PATCH http://localhost:3000/actors/2.json
Content-Type: application/json

{
  "gender":"male",
  "age": 12
}

### delete actor

DELETE http://localhost:3000/movies/14


