@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxODQ2NzR9.soxNiX6W5zN8qMoP1_0-IwwhV8xdctJAVthpr4ynbCs

POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "hello,up dolly",
  "year": 2011,
  "plot": "nothing important",
  "director": "bob saget",
  "english": true
}

###
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name":"l",
  "last_name":"snider",
  "gender":"male",
  "age":"13",
  "known_for":"something"
}

### updating movies
PATCH http://localhost:3000/actors/14.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "last_name":"pitman"
}

###
PATCH http://localhost:3000/actors/2.json
Content-Type: application/json

{
  "gender":"male",
  "age": 12
}

### delete actor

DELETE http://localhost:3000/movies/14


### users create (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":"larry",
  "email":"larry@example.com",
  "password":"password",
  "password_confirmation":"password"
}

### login
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email":"bob@example.com",
  "password":"password"
}

### index
GET http://localhost:3000/movies.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### create moviegenre 
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id":3,
  "genre_id":3
}
